services:
  web:
    labels:
      experiment.id: "attack_t1498_v1"
      event.label: "malicious"
      scenario.id: "T1498_APP_DOS"
      attack.technique: "T1498.002"
      attack.tactic: "Impact"

  proxy:
    labels:
      experiment.id: "attack_t1498_v1"
      event.label: "malicious"
      scenario.id: "T1498_APP_DOS"
      attack.technique: "T1498.002"
      attack.tactic: "Impact"
